#:schema node_modules/wrangler/config-schema.json
name = "scheduler"
main = "src/index.ts"
compatibility_date = "2024-11-27"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
#[triggers]
#crons = ["* * * * *"] # * * * * * = run every minute

[vars]
DATABASE_URL = "your-database-url"

[[scheduled]]
crons = ["0 3 * * *"]  # Cron pattern for scheduling the task
