import type { Metadata } from "next";
import "./globals.css";
import Holder from "@/components/layout/Holder";

export const metadata: Metadata = {
  title: "Syntax Error",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="luxury" lang="en">
      <body>
        <main className="w-full min-h-[100dvh] flex flex-col ">
          <Holder>{children}</Holder>
        </main>
      </body>
    </html>
  );
}
